a=int(input("enter 1st number:"))
b=int(input("enter 2nd number:"))
print("a+b=",a+b,"\n"
      "a-b=",a-b,"\n"
      "a*b=",a*b,"\n"
      "a/b=",a/b,'\n'
"a//b=",a//b,'\n'
      "a**b=",a**b,'\n'
      "a%b=",a%b)
